[package]
name = "bitgesellcore-rpc"
version = "0.1.1"
authors = [
    "Steven Roose <steven@stevenroose.org>",
    "Jean Pierre Dudey <jeandudey@hotmail.com>",
    "Dawid Ciężarkiewicz <dpc@dpc.pw>",
    "Naftali Murgor <nmurgor10@gmail.com>",
]
license = "CC0-1.0"
homepage = "https://github.com/naftalimurgor/rust-bitgesellcore-rpc/"
repository = "https://github.com/naftalimurgor/rust-bitgesellcore-rpc/"
description = "RPC client library for the Bitgesell Core JSON-RPC API."
keywords = ["crypto", "bitcoin", "bitcoin-core", "rpc", "bitgesell"]
readme = "README.md"
edition = "2018"

[lib]
name = "bitgesellcore_rpc"
path = "src/lib.rs"

[dependencies]
bitcoincore-rpc-json = { package = "bitgesellcore-rpc-json", version = "0.17.1", path = "../json" }

log = "0.4.5"
jsonrpc = "0.14.0"

# Used for deserialization of JSON.
serde = "1"
serde_json = "1"
bitcoin-private = "0.1.0"
